spring:
  application.name: time-tracker-spring
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com:
      privat:
        timetracker:
          aop: INFO